data_path:
  label_f: /home/yang1031/projects/error-aware-calling/data/illumina/label_tiny_10000

training:
  model_path: /home/yang1031/projects/error-aware-calling/errorprediction/model_saved
  out_predix: model_1encoder
  input_length: 99
  data_loader_chunk_size: 1000
  batch_size: 40
  train_ratio: 0.7
  embed_size: 54
  num_layers: 1
  heads: 6
  forward_expansion: 1024
  num_tokens: 216
  num_bases: 5
  num_class_1: 5
  num_class_2: 25
  dropout_rate: 0.5
  max_length: 99
  learning_rate: 0.001
  epochs: 100
  label_length: 20
  up_seq_len: 99
  drop_out: 0.1
  kmer: 3
